run:
  deadline: 10m
linters:
  disable-all: false
  enable-all: false
  enable:
    - megacheck
    - staticcheck
    - deadcode
    - varcheck
    - gosimple
    - unused
    - prealloc
    - scopelint
    - goimports
    - unconvert
    - govet
    - nakedret
    - structcheck
    - gosec
  disable:
    - maligned
    - interfacer
    - typecheck
    - dupl
    - gocritic

